apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.14/manifests/install.yaml
  - ./ingress.yaml
  - ./sso-external-secret.yaml

namespace: argocd

patchesJson6902:
  - target:
      kind: ConfigMap
      version: v1
      name: argocd-cm
    path: ./patches/argocd-cm.yaml

  - target:
      kind: ConfigMap
      version: v1
      name: argocd-rbac-cm
    path: ./patches/argocd-rbac-cm.yaml

  - target:
      kind: Deployment
      version: v1
      name: argocd-server
    path: ./patches/argocd-server-deployment.yaml
