apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.14/manifests/install.yaml
  - ./ingress.yaml
  - ./sso-external-secret.yaml
  - ./root-app.yaml

namespace: argocd

patchesJson6902:
  - target:
      kind: ConfigMap
      version: v1
      name: argocd-cm
    path: ./patches/argocd-cm.yaml

  - target:
      kind: Deployment
      version: v1
      name: argocd-server
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/command
        value: ["argocd-server", "--insecure"]
