apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: argocd-sso
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: argocd-sso
  data:
    - secretKey: dex.github.clientSecret
      remoteRef:
        key: github-oauth-client-secret
