- op: add
  path: /data
  value:
    url: https://cd.pauljs.io
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: $argocd-sso:dex.github.clientID
            clientSecret: $argocd-sso:dex.github.clientSecret
