name: Provision GKE Cluster

on:
  push:
    branches:
      - main

jobs:
  apply:
    runs-on: ubuntu-latest

    name: Apply Terraform plan

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      TF_VAR_project_id: ${{ secrets.PROJECT_ID }}
      TERRAFORM_PRE_RUN: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        chmod u+x ./kustomize
        mv ./kustomize /usr/local/bin/kustomize

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: terraform
          auto_approve: true
